create table midias_sociais (id bigint not null auto_increment, facebook varchar(255), instagram varchar(255), linkedin varchar(255), twitter varchar(255), primary key (id)) engine=InnoDB;
create table perfis (id bigint not null auto_increment, bio varchar(1000), interesses varchar(600), website varchar(120), pessoa_fisica_id bigint, pessoa_juridica_id bigint, midias_sociais_id bigint, servicos_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_fisicas (id bigint not null auto_increment, cpf varchar(11) not null, nome varchar(50) not null, sobrenome varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_juridicas (id bigint not null auto_increment, cnpj varchar(14) not null, nome_fantasia varchar(100) not null, nome_responsavel varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table servicos (id bigint not null auto_increment, design bit not null, edicao bit not null, fotografia bit not null, redacao bit not null, primary key (id)) engine=InnoDB;
create table usuarios (id bigint not null auto_increment, email varchar(120) not null, password varchar(255) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
alter table pessoas_fisicas add constraint UK_nv4b5mujx3ocaantaao376hh5 unique (cpf);
alter table pessoas_juridicas add constraint UK_3b52maoq31nh35irr04i3xpfq unique (cnpj);
alter table usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table perfis add constraint FKiw4l2kc81hsda88lapkvdhxx1 foreign key (pessoa_fisica_id) references pessoas_fisicas (id);
alter table perfis add constraint FKbercfoncmg21ym5933c3boejg foreign key (pessoa_juridica_id) references pessoas_juridicas (id);
alter table perfis add constraint FK9xyvy6kdb8wd5xhhxwg21uoi6 foreign key (midias_sociais_id) references midias_sociais (id);
alter table perfis add constraint FKpjxkxj4itchehn4kdfj8l4smo foreign key (servicos_id) references servicos (id);
alter table pessoas_fisicas add constraint FKhe8d8t6jpu63n3g8f27pwh90u foreign key (perfil_id) references perfis (id);
alter table pessoas_juridicas add constraint FKpxljbx680fm106op2pew4alrm foreign key (perfil_id) references perfis (id);
alter table usuarios add constraint FKo1pfk0lndmxikb7rieaypdjp0 foreign key (perfil_id) references perfis (id);
create table midias_sociais (id bigint not null auto_increment, facebook varchar(255), instagram varchar(255), linkedin varchar(255), twitter varchar(255), primary key (id)) engine=InnoDB;
create table perfis (id bigint not null auto_increment, bio varchar(1000), interesses varchar(600), website varchar(120), pessoa_fisica_id bigint, pessoa_juridica_id bigint, midias_sociais_id bigint, servicos_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_fisicas (id bigint not null auto_increment, cpf varchar(11) not null, nome varchar(50) not null, sobrenome varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_juridicas (id bigint not null auto_increment, cnpj varchar(14) not null, nome_fantasia varchar(100) not null, nome_responsavel varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table servicos (id bigint not null auto_increment, design bit not null, edicao bit not null, fotografia bit not null, redacao bit not null, primary key (id)) engine=InnoDB;
create table usuarios (id bigint not null auto_increment, email varchar(120) not null, password varchar(255) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
alter table pessoas_fisicas add constraint UK_nv4b5mujx3ocaantaao376hh5 unique (cpf);
alter table pessoas_juridicas add constraint UK_3b52maoq31nh35irr04i3xpfq unique (cnpj);
alter table usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table perfis add constraint FKiw4l2kc81hsda88lapkvdhxx1 foreign key (pessoa_fisica_id) references pessoas_fisicas (id);
alter table perfis add constraint FKbercfoncmg21ym5933c3boejg foreign key (pessoa_juridica_id) references pessoas_juridicas (id);
alter table perfis add constraint FK9xyvy6kdb8wd5xhhxwg21uoi6 foreign key (midias_sociais_id) references midias_sociais (id);
alter table perfis add constraint FKpjxkxj4itchehn4kdfj8l4smo foreign key (servicos_id) references servicos (id);
alter table pessoas_fisicas add constraint FKhe8d8t6jpu63n3g8f27pwh90u foreign key (perfil_id) references perfis (id);
alter table pessoas_juridicas add constraint FKpxljbx680fm106op2pew4alrm foreign key (perfil_id) references perfis (id);
alter table usuarios add constraint FKo1pfk0lndmxikb7rieaypdjp0 foreign key (perfil_id) references perfis (id);
create table midias_sociais (id bigint not null auto_increment, facebook varchar(255), instagram varchar(255), linkedin varchar(255), twitter varchar(255), primary key (id)) engine=InnoDB;
create table perfis (id bigint not null auto_increment, bio varchar(1000), interesses varchar(600), website varchar(120), pessoa_fisica_id bigint, pessoa_juridica_id bigint, midias_sociais_id bigint, servicos_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_fisicas (id bigint not null auto_increment, cpf varchar(11) not null, nome varchar(50) not null, sobrenome varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_juridicas (id bigint not null auto_increment, cnpj varchar(14) not null, nome_fantasia varchar(100) not null, nome_responsavel varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table servicos (id bigint not null auto_increment, design bit not null, edicao bit not null, fotografia bit not null, redacao bit not null, primary key (id)) engine=InnoDB;
create table usuarios (id bigint not null auto_increment, email varchar(120) not null, password varchar(255) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
alter table pessoas_fisicas add constraint UK_nv4b5mujx3ocaantaao376hh5 unique (cpf);
alter table pessoas_juridicas add constraint UK_3b52maoq31nh35irr04i3xpfq unique (cnpj);
alter table usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table perfis add constraint FKiw4l2kc81hsda88lapkvdhxx1 foreign key (pessoa_fisica_id) references pessoas_fisicas (id);
alter table perfis add constraint FKbercfoncmg21ym5933c3boejg foreign key (pessoa_juridica_id) references pessoas_juridicas (id);
alter table perfis add constraint FK9xyvy6kdb8wd5xhhxwg21uoi6 foreign key (midias_sociais_id) references midias_sociais (id);
alter table perfis add constraint FKpjxkxj4itchehn4kdfj8l4smo foreign key (servicos_id) references servicos (id);
alter table pessoas_fisicas add constraint FKhe8d8t6jpu63n3g8f27pwh90u foreign key (perfil_id) references perfis (id);
alter table pessoas_juridicas add constraint FKpxljbx680fm106op2pew4alrm foreign key (perfil_id) references perfis (id);
alter table usuarios add constraint FKo1pfk0lndmxikb7rieaypdjp0 foreign key (perfil_id) references perfis (id);
#INSERT INTO tb_genre (name) VALUES ('Shooter');
#INSERT INTO tb_genre (name) VALUES ('MOBA');
#INSERT INTO tb_game (title, platform, genre_id) VALUES ('The Witcher 3', 2, 3);
#INSERT INTO tb_game (title, platform, genre_id) VALUES ('League of Legends', 0, 2);
#INSERT INTO tb_record (game_id, name, age, moment) VALUES (3, 'Tulio', 44, TIMESTAMP WITH TIME ZONE '2020-07-21T20:59:19Z');
#INSERT INTO tb_record (game_id, name, age, moment) VALUES (11, 'Alex', 33, TIMESTAMP WITH TIME ZONE '2020-06-20T20:30:26Z');
create table midias_sociais (id bigint not null auto_increment, facebook varchar(255), instagram varchar(255), linkedin varchar(255), twitter varchar(255), primary key (id)) engine=InnoDB;
create table perfis (id bigint not null auto_increment, bio varchar(1000), interesses varchar(600), website varchar(120), pessoa_fisica_id bigint, pessoa_juridica_id bigint, midias_sociais_id bigint, servicos_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_fisicas (id bigint not null auto_increment, cpf varchar(11) not null, nome varchar(50) not null, sobrenome varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_juridicas (id bigint not null auto_increment, cnpj varchar(14) not null, nome_fantasia varchar(100) not null, nome_responsavel varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table servicos (id bigint not null auto_increment, design bit not null, edicao bit not null, fotografia bit not null, redacao bit not null, primary key (id)) engine=InnoDB;
create table usuarios (id bigint not null auto_increment, email varchar(120) not null, password varchar(255) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
alter table pessoas_fisicas add constraint UK_nv4b5mujx3ocaantaao376hh5 unique (cpf);
alter table pessoas_juridicas add constraint UK_3b52maoq31nh35irr04i3xpfq unique (cnpj);
alter table usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table perfis add constraint FKiw4l2kc81hsda88lapkvdhxx1 foreign key (pessoa_fisica_id) references pessoas_fisicas (id);
alter table perfis add constraint FKbercfoncmg21ym5933c3boejg foreign key (pessoa_juridica_id) references pessoas_juridicas (id);
alter table perfis add constraint FK9xyvy6kdb8wd5xhhxwg21uoi6 foreign key (midias_sociais_id) references midias_sociais (id);
alter table perfis add constraint FKpjxkxj4itchehn4kdfj8l4smo foreign key (servicos_id) references servicos (id);
alter table pessoas_fisicas add constraint FKhe8d8t6jpu63n3g8f27pwh90u foreign key (perfil_id) references perfis (id);
alter table pessoas_juridicas add constraint FKpxljbx680fm106op2pew4alrm foreign key (perfil_id) references perfis (id);
alter table usuarios add constraint FKo1pfk0lndmxikb7rieaypdjp0 foreign key (perfil_id) references perfis (id);
#INSERT INTO tb_genre (name) VALUES ('Shooter');
#INSERT INTO tb_genre (name) VALUES ('MOBA');
#INSERT INTO tb_game (title, platform, genre_id) VALUES ('The Witcher 3', 2, 3);
#INSERT INTO tb_game (title, platform, genre_id) VALUES ('League of Legends', 0, 2);
#INSERT INTO tb_record (game_id, name, age, moment) VALUES (3, 'Tulio', 44, TIMESTAMP WITH TIME ZONE '2020-07-21T20:59:19Z');
#INSERT INTO tb_record (game_id, name, age, moment) VALUES (11, 'Alex', 33, TIMESTAMP WITH TIME ZONE '2020-06-20T20:30:26Z');
create table midias_sociais (id bigint not null auto_increment, facebook varchar(255), instagram varchar(255), linkedin varchar(255), twitter varchar(255), primary key (id)) engine=InnoDB;
create table perfis (id bigint not null auto_increment, bio varchar(1000), interesses varchar(600), website varchar(120), pessoa_fisica_id bigint, pessoa_juridica_id bigint, midias_sociais_id bigint, servicos_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_fisicas (id bigint not null auto_increment, cpf varchar(11) not null, nome varchar(50) not null, sobrenome varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_juridicas (id bigint not null auto_increment, cnpj varchar(14) not null, nome_fantasia varchar(100) not null, nome_responsavel varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table servicos (id bigint not null auto_increment, design bit not null, edicao bit not null, fotografia bit not null, redacao bit not null, primary key (id)) engine=InnoDB;
create table usuarios (id bigint not null auto_increment, email varchar(120) not null, password varchar(255) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
alter table pessoas_fisicas add constraint UK_nv4b5mujx3ocaantaao376hh5 unique (cpf);
alter table pessoas_juridicas add constraint UK_3b52maoq31nh35irr04i3xpfq unique (cnpj);
alter table usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table perfis add constraint FKiw4l2kc81hsda88lapkvdhxx1 foreign key (pessoa_fisica_id) references pessoas_fisicas (id);
alter table perfis add constraint FKbercfoncmg21ym5933c3boejg foreign key (pessoa_juridica_id) references pessoas_juridicas (id);
alter table perfis add constraint FK9xyvy6kdb8wd5xhhxwg21uoi6 foreign key (midias_sociais_id) references midias_sociais (id);
alter table perfis add constraint FKpjxkxj4itchehn4kdfj8l4smo foreign key (servicos_id) references servicos (id);
alter table pessoas_fisicas add constraint FKhe8d8t6jpu63n3g8f27pwh90u foreign key (perfil_id) references perfis (id);
alter table pessoas_juridicas add constraint FKpxljbx680fm106op2pew4alrm foreign key (perfil_id) references perfis (id);
alter table usuarios add constraint FKo1pfk0lndmxikb7rieaypdjp0 foreign key (perfil_id) references perfis (id);
#INSERT INTO tb_genre (name) VALUES ('Shooter');
#INSERT INTO tb_genre (name) VALUES ('MOBA');
#INSERT INTO tb_game (title, platform, genre_id) VALUES ('The Witcher 3', 2, 3);
#INSERT INTO tb_game (title, platform, genre_id) VALUES ('League of Legends', 0, 2);
#INSERT INTO tb_record (game_id, name, age, moment) VALUES (3, 'Tulio', 44, TIMESTAMP WITH TIME ZONE '2020-07-21T20:59:19Z');
#INSERT INTO tb_record (game_id, name, age, moment) VALUES (11, 'Alex', 33, TIMESTAMP WITH TIME ZONE '2020-06-20T20:30:26Z');
create table midias_sociais (id bigint not null auto_increment, facebook varchar(255), instagram varchar(255), linkedin varchar(255), twitter varchar(255), primary key (id)) engine=InnoDB;
create table perfis (id bigint not null auto_increment, bio varchar(1000), interesses varchar(600), website varchar(120), pessoa_fisica_id bigint, pessoa_juridica_id bigint, midias_sociais_id bigint, servicos_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_fisicas (id bigint not null auto_increment, cpf varchar(11) not null, nome varchar(50) not null, sobrenome varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_juridicas (id bigint not null auto_increment, cnpj varchar(14) not null, nome_fantasia varchar(100) not null, nome_responsavel varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table servicos (id bigint not null auto_increment, design bit not null, edicao bit not null, fotografia bit not null, redacao bit not null, primary key (id)) engine=InnoDB;
create table usuarios (id bigint not null auto_increment, email varchar(120) not null, password varchar(255) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
alter table pessoas_fisicas add constraint UK_nv4b5mujx3ocaantaao376hh5 unique (cpf);
alter table pessoas_juridicas add constraint UK_3b52maoq31nh35irr04i3xpfq unique (cnpj);
alter table usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table perfis add constraint FKiw4l2kc81hsda88lapkvdhxx1 foreign key (pessoa_fisica_id) references pessoas_fisicas (id);
alter table perfis add constraint FKbercfoncmg21ym5933c3boejg foreign key (pessoa_juridica_id) references pessoas_juridicas (id);
alter table perfis add constraint FK9xyvy6kdb8wd5xhhxwg21uoi6 foreign key (midias_sociais_id) references midias_sociais (id);
alter table perfis add constraint FKpjxkxj4itchehn4kdfj8l4smo foreign key (servicos_id) references servicos (id);
alter table pessoas_fisicas add constraint FKhe8d8t6jpu63n3g8f27pwh90u foreign key (perfil_id) references perfis (id);
alter table pessoas_juridicas add constraint FKpxljbx680fm106op2pew4alrm foreign key (perfil_id) references perfis (id);
alter table usuarios add constraint FKo1pfk0lndmxikb7rieaypdjp0 foreign key (perfil_id) references perfis (id);
#INSERT INTO tb_genre (name) VALUES ('Shooter');
#INSERT INTO tb_genre (name) VALUES ('MOBA');
#INSERT INTO tb_game (title, platform, genre_id) VALUES ('The Witcher 3', 2, 3);
#INSERT INTO tb_game (title, platform, genre_id) VALUES ('League of Legends', 0, 2);
#INSERT INTO tb_record (game_id, name, age, moment) VALUES (3, 'Tulio', 44, TIMESTAMP WITH TIME ZONE '2020-07-21T20:59:19Z');
#INSERT INTO tb_record (game_id, name, age, moment) VALUES (11, 'Alex', 33, TIMESTAMP WITH TIME ZONE '2020-06-20T20:30:26Z');
create table midias_sociais (id bigint not null auto_increment, facebook varchar(255), instagram varchar(255), linkedin varchar(255), twitter varchar(255), primary key (id)) engine=InnoDB;
create table perfis (id bigint not null auto_increment, bio varchar(1000), interesses varchar(600), website varchar(120), pessoa_fisica_id bigint, pessoa_juridica_id bigint, midias_sociais_id bigint, servicos_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_fisicas (id bigint not null auto_increment, cpf varchar(11) not null, nome varchar(50) not null, sobrenome varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_juridicas (id bigint not null auto_increment, cnpj varchar(14) not null, nome_fantasia varchar(100) not null, nome_responsavel varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table servicos (id bigint not null auto_increment, design bit not null, edicao bit not null, fotografia bit not null, redacao bit not null, primary key (id)) engine=InnoDB;
create table usuarios (id bigint not null auto_increment, email varchar(120) not null, password varchar(255) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
alter table pessoas_fisicas add constraint UK_nv4b5mujx3ocaantaao376hh5 unique (cpf);
alter table pessoas_juridicas add constraint UK_3b52maoq31nh35irr04i3xpfq unique (cnpj);
alter table usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table perfis add constraint FKiw4l2kc81hsda88lapkvdhxx1 foreign key (pessoa_fisica_id) references pessoas_fisicas (id);
alter table perfis add constraint FKbercfoncmg21ym5933c3boejg foreign key (pessoa_juridica_id) references pessoas_juridicas (id);
alter table perfis add constraint FK9xyvy6kdb8wd5xhhxwg21uoi6 foreign key (midias_sociais_id) references midias_sociais (id);
alter table perfis add constraint FKpjxkxj4itchehn4kdfj8l4smo foreign key (servicos_id) references servicos (id);
alter table pessoas_fisicas add constraint FKhe8d8t6jpu63n3g8f27pwh90u foreign key (perfil_id) references perfis (id);
alter table pessoas_juridicas add constraint FKpxljbx680fm106op2pew4alrm foreign key (perfil_id) references perfis (id);
alter table usuarios add constraint FKo1pfk0lndmxikb7rieaypdjp0 foreign key (perfil_id) references perfis (id);
#INSERT INTO tb_genre (name) VALUES ('Shooter');
#INSERT INTO tb_genre (name) VALUES ('MOBA');
#INSERT INTO tb_game (title, platform, genre_id) VALUES ('The Witcher 3', 2, 3);
#INSERT INTO tb_game (title, platform, genre_id) VALUES ('League of Legends', 0, 2);
#INSERT INTO tb_record (game_id, name, age, moment) VALUES (3, 'Tulio', 44, TIMESTAMP WITH TIME ZONE '2020-07-21T20:59:19Z');
#INSERT INTO tb_record (game_id, name, age, moment) VALUES (11, 'Alex', 33, TIMESTAMP WITH TIME ZONE '2020-06-20T20:30:26Z');
create table midias_sociais (id bigint not null auto_increment, facebook varchar(255), instagram varchar(255), linkedin varchar(255), twitter varchar(255), primary key (id)) engine=InnoDB;
create table perfis (id bigint not null auto_increment, bio varchar(1000), interesses varchar(600), website varchar(120), pessoa_fisica_id bigint, pessoa_juridica_id bigint, midias_sociais_id bigint, servicos_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_fisicas (id bigint not null auto_increment, cpf varchar(11) not null, nome varchar(50) not null, sobrenome varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table pessoas_juridicas (id bigint not null auto_increment, cnpj varchar(14) not null, nome_fantasia varchar(100) not null, nome_responsavel varchar(100) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
create table servicos (id bigint not null auto_increment, design bit not null, edicao bit not null, fotografia bit not null, redacao bit not null, primary key (id)) engine=InnoDB;
create table usuarios (id bigint not null auto_increment, email varchar(120) not null, password varchar(255) not null, perfil_id bigint, primary key (id)) engine=InnoDB;
alter table pessoas_fisicas add constraint UK_nv4b5mujx3ocaantaao376hh5 unique (cpf);
alter table pessoas_juridicas add constraint UK_3b52maoq31nh35irr04i3xpfq unique (cnpj);
alter table usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table perfis add constraint FKiw4l2kc81hsda88lapkvdhxx1 foreign key (pessoa_fisica_id) references pessoas_fisicas (id);
alter table perfis add constraint FKbercfoncmg21ym5933c3boejg foreign key (pessoa_juridica_id) references pessoas_juridicas (id);
alter table perfis add constraint FK9xyvy6kdb8wd5xhhxwg21uoi6 foreign key (midias_sociais_id) references midias_sociais (id);
alter table perfis add constraint FKpjxkxj4itchehn4kdfj8l4smo foreign key (servicos_id) references servicos (id);
alter table pessoas_fisicas add constraint FKhe8d8t6jpu63n3g8f27pwh90u foreign key (perfil_id) references perfis (id);
alter table pessoas_juridicas add constraint FKpxljbx680fm106op2pew4alrm foreign key (perfil_id) references perfis (id);
alter table usuarios add constraint FKo1pfk0lndmxikb7rieaypdjp0 foreign key (perfil_id) references perfis (id);
INSERT INTO usuarios (email, password) VALUES ('user1@teste.com', '!123Abcde');
INSERT INTO usuarios (email, password) VALUES ('user2@teste.com', '!123Abcde');
create table contacts_available_for_jobs (id bigint not null auto_increment, email bit, facebook bit, instagram bit, linkedin bit, other varchar(255), twitter bit, primary key (id)) engine=MyISAM;
create table midias_sociais (id bigint not null auto_increment, facebook varchar(255), instagram varchar(255), linkedin varchar(255), twitter varchar(255), primary key (id)) engine=MyISAM;
create table perfis (id bigint not null auto_increment, bio varchar(1000), interesses varchar(600), website varchar(120), pessoa_fisica_id bigint, pessoa_juridica_id bigint, midias_sociais_id bigint, servicos_id bigint, primary key (id)) engine=MyISAM;
create table pessoas_fisicas (id bigint not null auto_increment, cpf varchar(11) not null, nome varchar(50) not null, sobrenome varchar(100) not null, perfil_id bigint, primary key (id)) engine=MyISAM;
create table pessoas_juridicas (id bigint not null auto_increment, cnpj varchar(14) not null, nome_fantasia varchar(100) not null, nome_responsavel varchar(100) not null, perfil_id bigint, primary key (id)) engine=MyISAM;
create table servicos (id bigint not null auto_increment, design bit not null, edicao bit not null, fotografia bit not null, ilustracao bit not null, redacao bit not null, primary key (id)) engine=MyISAM;
create table usuarios (id bigint not null auto_increment, email varchar(120) not null, password varchar(255) not null, perfil_id bigint, primary key (id)) engine=MyISAM;
create table vagas (id bigint not null auto_increment, description varchar(255) not null, payment_to_negotiate bit, payment_type varchar(255) not null, price decimal(19,2) not null, status_vaga varchar(255), title_job varchar(255), contact_forms_id bigint, perfil_id bigint, type_job_id bigint not null, primary key (id)) engine=MyISAM;
alter table pessoas_fisicas add constraint UK_nv4b5mujx3ocaantaao376hh5 unique (cpf);
alter table pessoas_juridicas add constraint UK_3b52maoq31nh35irr04i3xpfq unique (cnpj);
alter table usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table perfis add constraint FKiw4l2kc81hsda88lapkvdhxx1 foreign key (pessoa_fisica_id) references pessoas_fisicas (id);
alter table perfis add constraint FKbercfoncmg21ym5933c3boejg foreign key (pessoa_juridica_id) references pessoas_juridicas (id);
alter table perfis add constraint FK9xyvy6kdb8wd5xhhxwg21uoi6 foreign key (midias_sociais_id) references midias_sociais (id);
alter table perfis add constraint FKpjxkxj4itchehn4kdfj8l4smo foreign key (servicos_id) references servicos (id);
alter table pessoas_fisicas add constraint FKhe8d8t6jpu63n3g8f27pwh90u foreign key (perfil_id) references perfis (id);
alter table pessoas_juridicas add constraint FKpxljbx680fm106op2pew4alrm foreign key (perfil_id) references perfis (id);
alter table usuarios add constraint FKo1pfk0lndmxikb7rieaypdjp0 foreign key (perfil_id) references perfis (id);
alter table vagas add constraint FKomql0oxpjgylv3mods9830rxj foreign key (contact_forms_id) references contacts_available_for_jobs (id);
alter table vagas add constraint FKnkb1xdjtcv27olwe7fnkcces8 foreign key (perfil_id) references perfis (id);
alter table vagas add constraint FKbbc027ac5i7bn93iyj816oxau foreign key (type_job_id) references servicos (id);
create table contacts_available_for_jobs (id bigint not null auto_increment, email bit, facebook bit, instagram bit, linkedin bit, other varchar(255), twitter bit, primary key (id)) engine=MyISAM;
create table midias_sociais (id bigint not null auto_increment, facebook varchar(255), instagram varchar(255), linkedin varchar(255), twitter varchar(255), primary key (id)) engine=MyISAM;
create table perfis (id bigint not null auto_increment, bio varchar(1000), interesses varchar(600), website varchar(120), pessoa_fisica_id bigint, pessoa_juridica_id bigint, midias_sociais_id bigint, servicos_id bigint, primary key (id)) engine=MyISAM;
create table pessoas_fisicas (id bigint not null auto_increment, cpf varchar(11) not null, nome varchar(50) not null, sobrenome varchar(100) not null, perfil_id bigint, primary key (id)) engine=MyISAM;
create table pessoas_juridicas (id bigint not null auto_increment, cnpj varchar(14) not null, nome_fantasia varchar(100) not null, nome_responsavel varchar(100) not null, perfil_id bigint, primary key (id)) engine=MyISAM;
create table servicos (id bigint not null auto_increment, design bit not null, edicao bit not null, fotografia bit not null, ilustracao bit not null, redacao bit not null, primary key (id)) engine=MyISAM;
create table usuarios (id bigint not null auto_increment, email varchar(120) not null, password varchar(255) not null, perfil_id bigint, primary key (id)) engine=MyISAM;
create table vagas (id bigint not null auto_increment, description varchar(255) not null, payment_to_negotiate bit, payment_type varchar(255) not null, price decimal(19,2) not null, status_vaga varchar(255), title_job varchar(255), contact_forms_id bigint, perfil_id bigint, type_job_id bigint not null, primary key (id)) engine=MyISAM;
alter table pessoas_fisicas add constraint UK_nv4b5mujx3ocaantaao376hh5 unique (cpf);
alter table pessoas_juridicas add constraint UK_3b52maoq31nh35irr04i3xpfq unique (cnpj);
alter table usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table perfis add constraint FKiw4l2kc81hsda88lapkvdhxx1 foreign key (pessoa_fisica_id) references pessoas_fisicas (id);
alter table perfis add constraint FKbercfoncmg21ym5933c3boejg foreign key (pessoa_juridica_id) references pessoas_juridicas (id);
alter table perfis add constraint FK9xyvy6kdb8wd5xhhxwg21uoi6 foreign key (midias_sociais_id) references midias_sociais (id);
alter table perfis add constraint FKpjxkxj4itchehn4kdfj8l4smo foreign key (servicos_id) references servicos (id);
alter table pessoas_fisicas add constraint FKhe8d8t6jpu63n3g8f27pwh90u foreign key (perfil_id) references perfis (id);
alter table pessoas_juridicas add constraint FKpxljbx680fm106op2pew4alrm foreign key (perfil_id) references perfis (id);
alter table usuarios add constraint FKo1pfk0lndmxikb7rieaypdjp0 foreign key (perfil_id) references perfis (id);
alter table vagas add constraint FKomql0oxpjgylv3mods9830rxj foreign key (contact_forms_id) references contacts_available_for_jobs (id);
alter table vagas add constraint FKnkb1xdjtcv27olwe7fnkcces8 foreign key (perfil_id) references perfis (id);
alter table vagas add constraint FKbbc027ac5i7bn93iyj816oxau foreign key (type_job_id) references servicos (id);
create table contacts_available_for_jobs (id bigint not null auto_increment, email bit, facebook bit, instagram bit, linkedin bit, other varchar(255), twitter bit, primary key (id)) engine=MyISAM;
create table midias_sociais (id bigint not null auto_increment, facebook varchar(255), instagram varchar(255), linkedin varchar(255), twitter varchar(255), primary key (id)) engine=MyISAM;
create table perfis (id bigint not null auto_increment, bio varchar(1000), interesses varchar(600), website varchar(120), pessoa_fisica_id bigint, pessoa_juridica_id bigint, midias_sociais_id bigint, servicos_id bigint, primary key (id)) engine=MyISAM;
create table pessoas_fisicas (id bigint not null auto_increment, cpf varchar(11) not null, nome varchar(50) not null, sobrenome varchar(100) not null, perfil_id bigint, primary key (id)) engine=MyISAM;
create table pessoas_juridicas (id bigint not null auto_increment, cnpj varchar(14) not null, nome_fantasia varchar(100) not null, nome_responsavel varchar(100) not null, perfil_id bigint, primary key (id)) engine=MyISAM;
create table servicos (id bigint not null auto_increment, design bit not null, edicao bit not null, fotografia bit not null, ilustracao bit not null, redacao bit not null, primary key (id)) engine=MyISAM;
create table usuarios (id bigint not null auto_increment, email varchar(120) not null, password varchar(255) not null, perfil_id bigint, primary key (id)) engine=MyISAM;
create table vagas (id bigint not null auto_increment, description varchar(255) not null, payment_to_negotiate bit, payment_type varchar(255) not null, price decimal(19,2) not null, status_vaga varchar(255), title_job varchar(255), contact_forms_id bigint, perfil_id bigint, type_job_id bigint not null, primary key (id)) engine=MyISAM;
alter table pessoas_fisicas add constraint UK_nv4b5mujx3ocaantaao376hh5 unique (cpf);
alter table pessoas_juridicas add constraint UK_3b52maoq31nh35irr04i3xpfq unique (cnpj);
alter table usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table perfis add constraint FKiw4l2kc81hsda88lapkvdhxx1 foreign key (pessoa_fisica_id) references pessoas_fisicas (id);
alter table perfis add constraint FKbercfoncmg21ym5933c3boejg foreign key (pessoa_juridica_id) references pessoas_juridicas (id);
alter table perfis add constraint FK9xyvy6kdb8wd5xhhxwg21uoi6 foreign key (midias_sociais_id) references midias_sociais (id);
alter table perfis add constraint FKpjxkxj4itchehn4kdfj8l4smo foreign key (servicos_id) references servicos (id);
alter table pessoas_fisicas add constraint FKhe8d8t6jpu63n3g8f27pwh90u foreign key (perfil_id) references perfis (id);
alter table pessoas_juridicas add constraint FKpxljbx680fm106op2pew4alrm foreign key (perfil_id) references perfis (id);
alter table usuarios add constraint FKo1pfk0lndmxikb7rieaypdjp0 foreign key (perfil_id) references perfis (id);
alter table vagas add constraint FKomql0oxpjgylv3mods9830rxj foreign key (contact_forms_id) references contacts_available_for_jobs (id);
alter table vagas add constraint FKnkb1xdjtcv27olwe7fnkcces8 foreign key (perfil_id) references perfis (id);
alter table vagas add constraint FKbbc027ac5i7bn93iyj816oxau foreign key (type_job_id) references servicos (id);
create table contacts_available_for_jobs (id bigint not null auto_increment, email bit, facebook bit, instagram bit, linkedin bit, other varchar(255), twitter bit, primary key (id)) engine=MyISAM;
create table midias_sociais (id bigint not null auto_increment, facebook varchar(255), instagram varchar(255), linkedin varchar(255), twitter varchar(255), primary key (id)) engine=MyISAM;
create table perfis (id bigint not null auto_increment, bio varchar(1000), interesses varchar(600), website varchar(120), pessoa_fisica_id bigint, pessoa_juridica_id bigint, midias_sociais_id bigint, servicos_id bigint, primary key (id)) engine=MyISAM;
create table pessoas_fisicas (id bigint not null auto_increment, cpf varchar(11) not null, nome varchar(50) not null, sobrenome varchar(100) not null, perfil_id bigint, primary key (id)) engine=MyISAM;
create table pessoas_juridicas (id bigint not null auto_increment, cnpj varchar(14) not null, nome_fantasia varchar(100) not null, nome_responsavel varchar(100) not null, perfil_id bigint, primary key (id)) engine=MyISAM;
create table servicos (id bigint not null auto_increment, design bit not null, edicao bit not null, fotografia bit not null, ilustracao bit not null, redacao bit not null, primary key (id)) engine=MyISAM;
create table usuarios (id bigint not null auto_increment, email varchar(120) not null, password varchar(255) not null, perfil_id bigint, primary key (id)) engine=MyISAM;
create table vagas (id bigint not null auto_increment, description varchar(255) not null, payment_to_negotiate bit, payment_type varchar(255) not null, price decimal(19,2) not null, status_vaga varchar(255), title_job varchar(255), contact_forms_id bigint, perfil_id bigint, type_job_id bigint not null, primary key (id)) engine=MyISAM;
alter table pessoas_fisicas add constraint UK_nv4b5mujx3ocaantaao376hh5 unique (cpf);
alter table pessoas_juridicas add constraint UK_3b52maoq31nh35irr04i3xpfq unique (cnpj);
alter table usuarios add constraint UK_kfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table perfis add constraint FKiw4l2kc81hsda88lapkvdhxx1 foreign key (pessoa_fisica_id) references pessoas_fisicas (id);
alter table perfis add constraint FKbercfoncmg21ym5933c3boejg foreign key (pessoa_juridica_id) references pessoas_juridicas (id);
alter table perfis add constraint FK9xyvy6kdb8wd5xhhxwg21uoi6 foreign key (midias_sociais_id) references midias_sociais (id);
alter table perfis add constraint FKpjxkxj4itchehn4kdfj8l4smo foreign key (servicos_id) references servicos (id);
alter table pessoas_fisicas add constraint FKhe8d8t6jpu63n3g8f27pwh90u foreign key (perfil_id) references perfis (id);
alter table pessoas_juridicas add constraint FKpxljbx680fm106op2pew4alrm foreign key (perfil_id) references perfis (id);
alter table usuarios add constraint FKo1pfk0lndmxikb7rieaypdjp0 foreign key (perfil_id) references perfis (id);
alter table vagas add constraint FKomql0oxpjgylv3mods9830rxj foreign key (contact_forms_id) references contacts_available_for_jobs (id);
alter table vagas add constraint FKnkb1xdjtcv27olwe7fnkcces8 foreign key (perfil_id) references perfis (id);
alter table vagas add constraint FKbbc027ac5i7bn93iyj816oxau foreign key (type_job_id) references servicos (id);
