package br.com.communicart.backendserver.model.enums;

public enum StatusVaga {
	ATIVA, DESATIVADA, BLOQUEADA, CONCLUIDA, EM_ANDAMENTO
}

//ATIVA - DISPONÍVEL PARA CANDIDATAR-SE
//DESATIVADA - QUANDO O CONTRATANTE DELETA A VAGA
//BLOQUEADA - QUANDO O USUARIO BLOQUEIA A VAGA PARA NINGUÉM VER
//CONCLUIDA - QUANDO JÁ FOI CONCLUIDO O TRABALHO
//EM_ANDAMENTO - INICIA-SE NO MOMENTO EM QUE O FREELANCER É SELECIONADO
//
